# Generated by Django 5.0.6 on 2024-06-19 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="industry",
        ),
    ]
