ARG PYTHON_VERSION=3.12-slim-bullseye

FROM python:${PYTHON_VERSION}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /code

WORKDIR /code

COPY requirements.txt /tmp/requirements.txt
RUN set -ex && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /root/.cache/
COPY . /code

# Apply database migrations
RUN python manage.py migrate --noinput

ENV SECRET_KEY "YqUW6J6EBBnAPkyhaWCLx8Xk3PWWjnkfJXbn5EyMp4zgwW4cCt"
RUN python manage.py collectstatic --noinput


EXPOSE 8000

CMD ["gunicorn", "--bind", ":8000", "--workers", "2", "typing_speed_game.wsgi"]
